sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fRLtRMyelqy79pNWJiZYCYt8QvKCPdo2e6srHnfDyZHqa/ZSQPhCy33dMBG88AB1xKCOY/ZFtlBVH7kNDaamZgNLX7HreoEKRiOYXlMevW1+QKFF4BWx9NoyLM6BIIKIMGVUNARX8WUJxD+Tuxqii9Gfvxoh1GZHg/BRyAHLIErYZpL1ICt+VxGAegPbQ8ECqXg5/g9trr+uhsgzIMAecagF/148XlC/jeq8J8LLNaIDdFKT5eXVGZf+WAfPKv63vLhs5Ruro1Z9xOS9AY6beJyVTvlKKqXE0QpYqWQltJjACRzOT0aMMLqdj29r4dXsOpW8qdhsFe561WVoEbZ7c1I7/p17NfhjRXwG9zo5V+4kxh/6w+HZR5S8sXP0mfJ0UPdZJe1h7ofdf3fvaxp0XapPeQ/A5xQ5DJRwWSOSW9M+0IbMNwIk2d80hEr0ZatB+iaTcQR7mBkWWNiklWOVDF8toKrthOzytr3mIZLOZ16lqGjYrWzE7jVGg+Vde8iMQYlcSv5GVbwWi/vXvR9hGSCQPdvcHq7vo2j0KHXPZq5h6HCjJfCQNeXIuj0conXuv88XwZz5crUb7r0S9PhZGBCxFo8twn8KS8S4tLZgmgOz+vCcoertout8/QL0TZjwz33R/mwlBVIsNmkw2N1HpivxO0yE7TzTGzVh9z2dtIU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Cardinal-s-Snuff-Box_5610
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy